#!/usr/bin/env python3
"""Generate README.md from workshop frontmatter.

Usage: python3 scripts/build_index.py          # write README.md
       python3 scripts/build_index.py --check  # exit 1 if README.md differs from generated output
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_staleness import grouped, status  # noqa: E402
from validate import LEVEL_ORDER, ROOT  # noqa: E402

MARKER = "<!-- GENERATED by scripts/build_index.py - do not edit by hand; it is rebuilt on every push to main. -->"
ICON = {"current": "✅", "outdated": "⚠️", "review": "⚠️", "archived": "🗄"}

INTRO = """# Avalanche Workshops by Team1

Community-maintained Avalanche workshops in multiple languages, curated by [Team1](https://team1.network). Add a workshop, translate one, or improve an existing one.

**Use a workshop:** pick one from the table, open `workshops/<slug>/<lang>/README.md`, follow it top to bottom. Slides, code, and recordings are linked from each workshop.

**Contribute:** copy `templates/workshop/README.md` to `workshops/<slug>/<lang>/`, fill in the frontmatter, open a pull request. See [CONTRIBUTING.md](CONTRIBUTING.md). Content is licensed CC BY 4.0, code samples MIT.

Sorted by level, then by each workshop's `order`.

Legend: ✅ current · ⚠️ outdated translation / needs review · 🗄 archived
"""


def people(entries):
    out = []
    for p in entries or []:
        name, url = (p.get("name"), p.get("url")) if isinstance(p, dict) else (p, None)
        out.append(f"[{name}]({url})" if url else str(name))
    return ", ".join(out)


def table(rows):
    if not rows:
        return "_none yet_\n"
    out = ["| Workshop | Level | Duration | Authors | Languages |", "|---|---|---|---|---|"]
    for slug, ws in rows:
        primary = ws["_primary"]
        fm = ws[primary][1]
        langs = " · ".join(f"[{lang}](workshops/{slug}/{lang}/README.md) {ICON[st]}"
                           for lang, (st, _) in sorted(ws.items()) if lang != "_primary")
        out.append(f"| [{fm.get('title', slug)}](workshops/{slug}/{primary}/README.md) | {fm.get('level', '')} | {fm.get('duration', '')} | {people(fm.get('authors'))} | {langs} |")
    return "\n".join(out) + "\n"


def build(root=ROOT):
    workshops = {}
    for slug, langs in grouped(root).items():
        fms = {lang: fm for lang, (_, fm) in langs.items()}
        originals = [lang for lang, fm in fms.items() if not fm.get("translated_from")]
        primary = "en" if "en" in fms else (originals or sorted(fms))[0]
        workshops[slug] = {lang: (status(path, fm, fms), fm) for lang, (path, fm) in langs.items()}
        workshops[slug]["_primary"] = primary
    def primary_fm(ws):
        return ws[ws["_primary"]][1]

    def key(item):
        fm = primary_fm(item[1])
        order = fm.get("order")
        return (LEVEL_ORDER.get(fm.get("level"), 99), order if isinstance(order, int) else 10**6, item[0])

    workshops = dict(sorted(workshops.items(), key=key))
    active = [(s, ws) for s, ws in workshops.items() if not primary_fm(ws).get("archived")]
    archived = [(s, ws) for s, ws in workshops.items() if primary_fm(ws).get("archived")]
    parts = [MARKER, "", INTRO, "## Workshops", "", table(active)]
    if archived:
        parts += ["## Archived", "", table(archived)]
    return "\n".join(parts)


if __name__ == "__main__":
    readme = ROOT / "README.md"
    content = build()
    if "--check" in sys.argv:
        if readme.exists() and readme.read_text(encoding="utf-8") == content:
            sys.exit(0)
        print("README.md is out of date - run: python3 scripts/build_index.py")
        sys.exit(1)
    readme.write_text(content, encoding="utf-8")
    print(f"wrote {readme}")
